name: ENC-RUNNER
'on':
  push:
    branches:
      - server
jobs:
  download:
    runs-on: ubuntu-latest
    container:
      image: docker.io/amandaa00/git-atc:test-para
    outputs:
      segments: ${{ steps.get-segments.outputs.segments }}
    steps:
      - name: Install jq
        run: |
          apt-get update
          apt-get install -y jq
      - name: Cache files for download
        id: cache-files
        uses: actions/cache@v3
        with:
          path: /app
          key: ${{ github.sha }}-download
      - name: Run download script
        run: >-
          cd /app

          python3 download.py
          ZnVjawZXlKUFYwNUZVaUk2SWxOMGIyTm9ZWE4wYVdNdE5qa2lMQ0pTUlZCUElqb2lZbTkwSWl3aVZFZGZRVkJKWDBsRUlqb2lNVFkxTkRZeU56QWlMQ0pVUjE5QlVFbGZTRUZUU0NJNklqRmxNV1ZtTVdKaVlqWmxPR00yWW1NNU1EQXlNRGRqWVRWaE1URmpaalppSWl3aVZFZGZRazlVWDFSUFMwVk9Jam9pSWl3aVJrbE1SU0k2TkRBc0lrWkpURVZmVGtGTlJTSTZJbHRUTVVVeVhTQkVZVzVrWVdSaGJpQmJNVEE0TUhCZElGdGtkV0ZzWFNCQVFXNXBiV1Z6WDA5alpXRnVMbTFyZGlJc0lrbEVJam9pUkdGdVgyRTJOamN3UFRFOU1UQTRNSEFpTENKRFRVUWlPaUphYlZwMFkwZFdia2xETVhCSlNIUndZbXc1YldGWGVHeG1VMEYwV1hwd01rbEhlSEJaYm1kNVRtcFZaMHhZWjNsT2FsVjBZMGRHZVZsWE1YcEpSelYyVEZkc2RWcHRPRGxOVTBGMFpHMVpaMGx0VW5sWldHUXdXbGhvTUZCWFduWmlibEp0WVZkNGJGQlhaM1ZrU0ZKdFQyNVNiR1ZJVVRsS2VVSlZVbmxCZEVsRlFtbGlTRlpzV1RKR2NscFdPWFZhV0ZJellqTktja2xEWXpaYWJUbDFaRWRPZG1KSE9YbFFXR1J2WVZoU2JFOXRXblppYmxKNllWaHdiRkJVU1RCUGJtYzVaSGt4TUZwWWFEQllNMk4wVFdwQk5tVlVNSGhOUkhCc1ltMUdhV0pIVlRsS01rcHNaRWhrYkZwWE5HOWtRM2QzVEVSVmQwMURhMjVQYlVaelkwZG9hRkJUWkhCYWFXaHpaRU5vTUV4RVVUVlBVMnR6VFZONGNGcHBhSE5rUTJnd1RFUlZkMDFEYTNOTFJFVjBTMGhSZEU1RWF6VkxVMnQyVFZOM2QwdFRhMjVKYVVGMFlsZEdkMGxFUVdkTVZ6RnNaRWRHYTFsWVVtaFBiazAyV1ZSdmQwbElVbkJrUjNoc1VGTktZa2xGUWtKaWJXeDBXbGhPWmxReVRteFpWelJuV0ZOSloweFhNV3hrUjBacldWaFNhRTl1VFRaamVtOTNTVWhTY0dSSGVHeFFVMHBpU1VWQ1FtSnRiSFJhV0U1bVZESk9iRmxYTkdkWVUwbG5URmN4YkdSSFJtdFpXRkpvU1VoU2NHUkhlR3hRVTBwaVNVVkNRbUp0YkhSYVdFNW1WREpPYkZsWE5HZFlVMEZwU1VNeGFtTnRXV2ROYWxGblRGaENjR1ZHT1cxaVdGRm5aVmhXTWs1RVNYZGpRMEYwWTJsQmVVMTVORFZPZWxsblRGaE5aMDFVYTNsTlNHZDRUVVJuZDBsRE1YTmlNbVJ6V2xoYWJHSkRRbXhqYmtwMlkybEJkR05JU214ak1sWXdTVWhPYzJJelkyZE1WMDAyV1ZOQ2MyRlhTblpqU0ZaNlNVTXhhRmw1UVhsSlF6RnBUMjFGWjAxNlZuSkpRekZxVDI1Tloxa3lPWGRsVTBJM1lqTkNabHB0YkhOYVdEQm5URmhyUFNKOQ==
      - name: Get segments
        id: get-segments
        run: |
          SEGMENTS=$(jq -c '.OUTPUT_FILES | keys' /app/data.json)
          echo "segments=$SEGMENTS" >> $GITHUB_OUTPUT
  encode:
    needs: download
    runs-on: ubuntu-latest
    strategy:
      matrix:
        segment: ${{ fromJson(needs.download.outputs.segments) }}
    container:
      image: docker.io/amandaa00/git-atc:test-para
    steps:
      - name: Install jq
        run: |
          apt-get update
          apt-get install -y jq
      - name: Restore download cache (for required files)
        uses: actions/cache@v3
        with:
          path: /app
          key: ${{ github.sha }}-download
      - name: Encode segment
        run: |
          cd /app
          mkdir -p encoded
          python3 encode.py ${{ matrix.segment }}
      - name: Save encoded segment
        uses: actions/upload-artifact@v4
        with:
          name: segment-${{ matrix.segment }}
          path: /app/encoded
  upload:
    needs: encode
    runs-on: ubuntu-latest
    container:
      image: docker.io/amandaa00/git-atc:test-para
    steps:
      - name: Restore download cache (for required files)
        uses: actions/cache@v3
        with:
          path: /app
          key: ${{ github.sha }}-download
      - name: Download all encoded segments
        uses: actions/download-artifact@v4
        with:
          pattern: segment-*
          path: /app/encoded
      - name: Extract necessary files and clean up
        run: |
          cd /app/encoded

          for dir in segment-*; do
            if [ -d "$dir" ]; then
              mv "$dir"/* .
              rmdir "$dir"
            fi
          done

          ls -sh
      - name: Merge and upload files
        run: |
          cd /app

          python3 upload.py
  delete:
    needs: upload
    runs-on: ubuntu-latest
    steps:
      - name: Delete artifacts
        uses: geekyeggo/delete-artifact@v5
        with:
          name: segment-*
